### ISSUE TITLE
npm install of 1.1.8 fails

### ISSUE THREAD

**Issue by timotm** [coolaj86/node-ssl-root-cas#10]
After 1.1.8 release, npm install of `ssl-root-cas` started to fail in postinstall phase.

It seems to be related to the fact that I have also `request` in my package.json. With minimal package.json containing only
```
  "dependencies": {
    "request": "^2.44.0",
    "ssl-root-cas": "^1.1.7"
  }
```
npm install fails about 8/10 times with an error like

```
> ssl-root-cas@1.1.8 postinstall /path_to_my_code/node_modules/ssl-root-cas
> node latest.js


module.js:340
    throw err;
          ^
Error: Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/path_to_my_code/node_modules/request/node_modules/hawk/node_modules/boom/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

To me it seems that the postinstall process tries to use top level request module which has not been completely installed yet.

I never saw this with 1.1.7.

Reproduces both on OS X 10.9 and Debian 7.

**Comment by coolaj86** [comment]
Closing since this was fixed. Reopen if you think we should try a different approach.
